abbreviations: false
adam_epsilon: 1.0e-06
autoconfig_path: /home/dunlap/Kaggle/NBME/input/nbme-2wbvmzdp/2wbvmzdp_13kelj6x/config.json
automodel_path: input/microsoft/deberta-v3-large
batch_size: 32
best_th: 0.52
best_th_score: 0.8894756103936844
check_n_steps: 5000
cv_split: groupkfold
decoder_lr: 5.0e-06
encoder_lr: 5.0e-06
epochs: 2
f1_inf: 0.8889468808309084
fc_dropout: 0.1
fold: 1
initial_lr: 1.1e-05
limit_train_batches: 1.0
max_len: 512
model: microsoft/deberta-v3-large
model_base: deberta
model_repo: microsoft/deberta-v3-large
num_folds: 5
num_workers: 8
precision: 16
pseudo_labels: <helper_fns.utils.dict2obj.<locals>.C object at 0x7fa97ed5a040>
seed: 42
th: 0.5
trn_fold:
- 1
- 2
- 3
- 4
wandb_project: ScoreClinicalNotes
warmup_steps: 0.01
weight_decay: 0.01
